title: Rangga Akhli
logo: /assets/img/headshot_circle.png
#description: International Relations and Security Studies | Data Science and Machine Learning
show_downloads: False
theme: jekyll-theme-minimal
